/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DydEFF8UYLc
 */
import Image from "next/image";
import Link from "next/link";

export function BlogPostLayout({ posts }) {
  const dateOptions = {
    year: "numeric",
    month: "long",
    day: "numeric",
  };

  return (
    <div key="1" className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
      {/* Most recent post */}
      {!posts[0] ? null : (
        <article className="mb-12">
          <Image
            alt="Featured post image"
            className="w-full h-64 md:h-96 object-cover rounded-lg"
            height={600}
            src="/placeholder.svg"
            style={{
              aspectRatio: "1200/600",
              objectFit: "cover",
            }}
            width={1200}
          />
          <div className="mt-6">
            <h1 className="text-3xl md:text-4xl font-bold">
              {posts[0].title.rendered}
            </h1>
            <p className="mt-2 text-gray-500">
              Published on{" "}
              {new Date(posts[0].date).toLocaleDateString("en-US", dateOptions)}{" "}
              {/* by
              <span className="font-medium"> John Doe</span> */}
            </p>
            {/* <p className="mt-4 text-lg text-gray-700">
              Artificial Intelligence (AI) is rapidly transforming our world.
              Remarkable breakthroughs in machine learning have led to...
            </p> */}
            <div
              className="mt-4 text-lg text-gray-700"
              dangerouslySetInnerHTML={{ __html: posts[0].excerpt.rendered }}
            />
            <Link
              className="mt-4 inline-block bg-cdiBlue text-white py-2 px-4 rounded hover:bg-cdiLightBlue hover:text-black"
              href={`/product-information/${posts[0].slug}/`}
            >
              Read More
            </Link>
          </div>
        </article>
      )}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div className="flex flex-col">
          <Image
            alt="Post image"
            className="w-full h-40 object-cover rounded-lg"
            height={200}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/200",
              objectFit: "cover",
            }}
            width={400}
          />
          <h2 className="mt-4 text-xl font-bold">
            Exploring Quantum Computing
          </h2>
          <p className="mt-2 text-gray-500">Published on January 28, 2024</p>
        </div>
        <div className="flex flex-col">
          <Image
            alt="Post image"
            className="w-full h-40 object-cover rounded-lg"
            height={200}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/200",
              objectFit: "cover",
            }}
            width={400}
          />
          <h2 className="mt-4 text-xl font-bold">
            The Rise of Augmented Reality
          </h2>
          <p className="mt-2 text-gray-500">Published on January 27, 2024</p>
        </div>
        <div className="flex flex-col">
          <Image
            alt="Post image"
            className="w-full h-40 object-cover rounded-lg"
            height={200}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/200",
              objectFit: "cover",
            }}
            width={400}
          />
          <h2 className="mt-4 text-xl font-bold">
            Understanding Blockchain Technology
          </h2>
          <p className="mt-2 text-gray-500">Published on January 26, 2024</p>
        </div>
      </div>
      <div className="grid grid-cols-1 gap-6 mt-6">
        <div className="flex flex-col md:flex-row">
          <Image
            alt="Post image"
            className="w-full h-64 md:w-1/2 object-cover rounded-lg"
            height={300}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width={400}
          />
          <div className="mt-4 md:mt-0 md:ml-4">
            <h2 className="text-xl font-bold">The Impact of 5G Technology</h2>
            <p className="mt-2 text-gray-500">
              Published on January 25, 2024 by
              <span className="font-medium">John Doe</span>
            </p>
            <p className="mt-2 text-gray-700">
              Discover how 5G technology is revolutionizing communication and
              the potential impact it could have on our daily lives.
            </p>
            <Link
              className="text-blue-600 hover:text-blue-800 mt-4 inline-block"
              href="#"
            >
              Read More
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
