/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uousp2Cdvwq
 */
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";

export function Currency({ setCurrencyCode }) {
  return (
    <form>
      <Select
        className="bg-white rounded-md shadow-md"
        onValueChange={(value) => setCurrencyCode(value)}
      >
        <SelectTrigger className="w-full text-black bg-white">
          <SelectValue placeholder="Currency" />
        </SelectTrigger>
        <SelectContent className="bg-white rounded-md shadow-md z-">
          <SelectItem value="CAD">CAD</SelectItem>
          <SelectItem value="USD">USD</SelectItem>
          <SelectItem value="EUR">EUR</SelectItem>
          <SelectItem value="GBP">GBP</SelectItem>
        </SelectContent>
      </Select>
    </form>
  );
}
