/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uousp2Cdvwq
 */
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { CartContext } from "@/lib/context/cartContext";
import { useContext } from "react";

export function Currency() {
  const { cart } = useContext(CartContext);
  const handleCurrencyUpdate = (e) => {
    if (e.target.value) {
      const id = e.target.value.toUpperCase();
      localStorage.setItem("currency", id);
      try {
        fetch(`/api/wc/store/currency/${id}`, {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
          },
        });
      } catch (error) {
        console.log(error);
      }
    }
  };
  return (
    <form onChange={handleCurrencyUpdate}>
      <Select className="bg-white rounded-md shadow-md">
        <SelectTrigger className="w-32 text-black bg-white">
          <SelectValue placeholder="Currency" />
        </SelectTrigger>
        <SelectContent className="bg-white rounded-md shadow-md">
          <SelectItem value="usd">USD</SelectItem>
          <SelectItem value="cad">CAD</SelectItem>
          <SelectItem value="eur">EUR</SelectItem>
          <SelectItem value="gbp">GBP</SelectItem>
          <SelectItem value="jpy">JPY</SelectItem>
        </SelectContent>
      </Select>
    </form>
  );
}
