/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Iem1wJ0Ks09
 */
import Link from "next/link";
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card";

export function FaqLayout() {
  return (
    <div className="grid min-h-screen w-full  lg:grid-cols-[280px_1fr] border-t border-b mb-4">
      <div className="hidden border-r bg-gray-100/40 lg:block ">
        <div className="flex h-full max-h-screen flex-col gap-2">
          <div className="flex h-[60px] items-center border-b px-6">
            <Link className="flex items-center gap-2 font-semibold" href="#">
              <span className="">CDI Furlers</span>
            </Link>
          </div>
          <div className="flex-1 overflow-auto py-2">
            <nav className="grid items-start px-4 text-sm font-medium">
              <Link
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 hover:bg-gray-200 "
                href="/faq#shipping"
              >
                Shipping Information
              </Link>
              <Link
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 hover:bg-gray-200 "
                href="/faq#delivery"
              >
                Delivery Details
              </Link>
              <Link
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 hover:bg-gray-200 "
                href="/faq#returns"
              >
                Return Policy
              </Link>
            </nav>
          </div>
        </div>
      </div>
      <div className="flex flex-col">
        <main
          className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6"
          id="shipping&delivery"
        >
          <div className="flex items-center gap-4">
            <h1 className="font-semibold text-lg md:text-xl">
              Frequently Asked Questions
            </h1>
          </div>
          <div className="flex flex-col md:grid md:grid-cols-6 gap-6">
            <div className="md:col-span-4 lg:col-span-3 xl:col-span-4 flex flex-col gap-6">
              <Card id="shipping">
                <CardHeader>
                  <CardTitle>General Queries</CardTitle>
                </CardHeader>
                <CardContent>
                  <h4 className="font-semibold">
                    What is the CDI furler warranty?
                  </h4>
                  <p className="text-sm text-gray-500 ">
                    <span>
                      The Flexible Furler is warranted to remain functional for
                      10 years from date of purchase. You must be the original
                      purchaser of the unit. If, during this period, any part
                      becomes non-functional, CDI will repair or replace it,
                      free of charge, except for the freight.
                    </span>
                    <p className="font-bold mt-2">
                      The Flexible Furler warranty covers:
                    </p>
                    <ul className="list-disc list-inside">
                      <li>
                        <span className="font-bold">At Sea:</span> All hazards
                        at sea, including winching against obstructions,
                        unseamanlike use, and dismastings. This warranty remains
                        in force for charter and other commercial operations. No
                        maintenance is required to keep the warranty in force.
                      </li>
                    </ul>
                    <p className="font-bold mt-2">
                      The Flexible Furler warranty does not cover:
                    </p>
                    <ul className="list-disc list-inside">
                      <li>
                        <span className="font-bold">At Sea:</span> Shipwreck,
                        collision and acts of God. The warranty is void if the
                        mast is not fixed in place vertically at all times while
                        the boat is in the water. Tipping the mast forward to
                        pass under bridges, power lines or other low clearance
                        obstructions voids the warranty.
                      </li>
                      <li className="mt-2">
                        <span className="font-bold">On Trailers:</span>{" "}
                        Collision; being dragged on the ground; improper stowage
                        resulting in kinks, bends and twists; and damage due to
                        the luff not being supported over its entire length.
                        (See trailering instructions.)
                      </li>
                      <li className="mt-2">
                        <span className="font-bold">Storage:</span> Any damage
                        caused by improper storage or handling when not at sea.
                        Luffs must be stored flat and straight, or warranty is
                        void. Kinks, twists, bends and breakage due to the luff
                        not being stored flat and straight are not covered.
                        Coiling or twisting the luff either to remove kinks and
                        bends, or for transport and storage in other than a flat
                        and straight condition voids the warranty.
                      </li>
                    </ul>
                  </p>
                  <h4 className="font-semibold mt-4">
                    How can I track my order?
                  </h4>
                  <p className="text-sm text-gray-500 ">
                    Once your order is placed and initial payment made, we will
                    email you your tracking numbers when the item is shipped.
                  </p>
                  <p className="text-sm text-gray-500 mt-2">
                    Please note that shipping rates are estimated and timelines
                    are approximate. Make sure to time the delivery of your CDI
                    track with installation as you must open your coiled track
                    within one week of receiving it.
                  </p>
                  <h4 className="font-semibold mt-4">
                    How sturdy is the Flexible Furler?
                  </h4>
                  <p className="text-sm text-gray-500 ">
                    CDI&apos;s durable one-piece urethane furling drum and
                    stainless steel drum cover keeps the furling line in place.
                    You can accidentally drop your anchor onto the Flexible
                    Furler drum and expect it to keep working!
                  </p>
                  <p className="text-sm text-gray-500 mt-2">
                    Our patented, one-piece UV stabilized PVC luff extrusion is
                    as stiff in torsion as a metal system, and yet can bend
                    without kinking, unlike metal systems. There are no joints
                    to fail and it is designed to be winched.
                  </p>
                  <h4 className="font-semibold mt-4">
                    What is the mainenance and storage of the Flexible Furler?
                  </h4>
                  <p className="text-sm text-gray-500 ">
                    The Flexible Furler is a set-it-and-forget-it furling and
                    reefing system. No routine maintenance is required, but an
                    occasional rinsing with fresh water is a good idea. We do
                    not use of wet lubricants, like grease, as such lubricants
                    can trap wear causing dirt particles in the bearing area.
                    Dry lubricants like Teflon sprays are fine to make furling
                    easier.
                  </p>
                  <h4 className="font-semibold mt-4">
                    How do I find the right size Flexible Furler for my sail?
                  </h4>
                  <p className="text-sm text-gray-500 ">
                    The Flexible Furler is designed to fit over your existing
                    forestay and can be used to both reef and furl your sail in
                    any wind condition. The Flexible Furler can be used with a
                    new or existing sail, but the sail must have #6 luff tape on
                    the leading edge rather than hanks.
                  </p>
                  <p className="text-sm text-gray-500 mt-2">
                    You will need to measure the pin-to-pin length of the
                    forestay, the diameter of the wire, and the diameter of the
                    turnbuckle pin. Use the table “Furler Size selection” on our
                    website to determine which system is right for your boat.
                  </p>
                  <p className="text-sm text-gray-500 mt-2">
                    For questions regarding hardware and instillation please
                    refer to “email”.
                  </p>
                </CardContent>
              </Card>
              <Card id="shipping">
                <CardHeader>
                  <CardTitle>Shipping Information</CardTitle>
                </CardHeader>
                <CardContent>
                  <h4 className="font-semibold">
                    How are shipping rates calculated?
                  </h4>
                  <p className="text-sm text-gray-500 ">
                    Shipping rates are estimated and timelines are approximate.
                    Please make sure to time the delivery of your CDI track with
                    installation as you must open your coiled track within one
                    week of receiving it.
                  </p>
                  <h4 className="font-semibold mt-4">
                    Are shipments shipped to a location or direct to my door?
                  </h4>
                  <p className="text-sm text-gray-500 ">
                    Our CDI furlers and tracks are shipped directly to your door
                    for a no-hassel pick up.
                  </p>
                  <h4 className="font-semibold mt-4">Can I track my order?</h4>
                  <p className="text-sm text-gray-500 ">
                    Yes, once your order has been shipped, you will receive a
                    tracking number via email.
                  </p>
                </CardContent>
              </Card>
              <Card id="delivery">
                <CardHeader>
                  <CardTitle>Delivery Details</CardTitle>
                </CardHeader>
                <CardContent>
                  <h4 className="font-semibold">
                    What delivery options do I have?
                  </h4>
                  <p className="text-sm text-gray-500 ">
                    We offer standard and express delivery options. You can
                    choose your preferred option at checkout.
                  </p>
                  <h4 className="font-semibold mt-4">
                    What if I&apos;m not home for delivery?
                  </h4>
                  <p className="text-sm text-gray-500 ">
                    If you&apos;re not home at the time of delivery, the courier
                    will leave a note with instructions on how to pick up your
                    order or reschedule delivery.
                  </p>
                  <h4 className="font-semibold mt-4">
                    How long does it take to receive my order?
                  </h4>
                  <p className="text-sm text-gray-500 ">
                    Delivery typically takes place up to 5 to 7 weeks after
                    order confirmation. We work hard to ensure you get your CDI
                    track within the stated time frame as indicated on your
                    invoice. Speak with a sale consultant if you have questions
                    about our current turn-around times or if you need your
                    hardware in a rush.
                  </p>
                </CardContent>
              </Card>
              <Card id="returns">
                <CardHeader>
                  <CardTitle>Return Policy</CardTitle>
                </CardHeader>
                <CardContent>
                  <h4 className="font-semibold">What is your return policy?</h4>
                  <p className="text-sm text-gray-500 ">
                    All CDI furler purchases once shipped are final. No returns
                    or exchanges allowed.
                  </p>
                  <h4 className="font-semibold mt-4">
                    What if my furler doesn&apos;y fit my sail?
                  </h4>
                  <p className="text-sm text-gray-500 ">
                    Please refer to the information available on the website
                    regarding size, installation, features to determine the
                    correct furler prior to purchasing.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}

function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 1-2 2H5a2 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 1 7.24 3h9.52a2 1.8 1.1L21" />
      <path d="M12 3v6" />
    </svg>
  );
}
