/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/935EgMPp0XE
 */
import Link from "next/link";
import {
  NavigationMenuLink,
  NavigationMenuItem,
  NavigationMenuTrigger,
  NavigationMenuContent,
  NavigationMenuList,
  NavigationMenu,
} from "@/components/ui/navigation-menu";

export function NavMenu() {
  return (
    <div className="flex items-center justify-between px-6 py-4 bg-white ">
      <Link className="flex items-center" href="#">
        <MountainIcon className="h-6 w-6" />
        <span className="sr-only">Acme Inc</span>
      </Link>
      <NavigationMenu className="hidden lg:flex">
        <NavigationMenuList>
          <NavigationMenuItem>
            <NavigationMenuLink className="px-4 py-2" href="#">
              Home
            </NavigationMenuLink>
          </NavigationMenuItem>
          <NavigationMenuItem>
            <NavigationMenuTrigger className="px-4 py-2">
              Services
            </NavigationMenuTrigger>
            <NavigationMenuContent className="w-[200px]">
              <NavigationMenuLink asChild>
                <Link className="block px-4 py-2" href="#">
                  Web Development
                </Link>
              </NavigationMenuLink>
              <NavigationMenuLink asChild>
                <Link className="block px-4 py-2" href="#">
                  App Development
                </Link>
              </NavigationMenuLink>
              <NavigationMenuLink asChild>
                <Link className="block px-4 py-2" href="#">
                  Design
                </Link>
              </NavigationMenuLink>
            </NavigationMenuContent>
          </NavigationMenuItem>
          <NavigationMenuItem>
            <NavigationMenuLink className="px-4 py-2" href="#">
              About Us
            </NavigationMenuLink>
          </NavigationMenuItem>
          <NavigationMenuItem>
            <NavigationMenuLink className="px-4 py-2" href="#">
              Contact Us
            </NavigationMenuLink>
          </NavigationMenuItem>
        </NavigationMenuList>
      </NavigationMenu>
    </div>
  );
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
