/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/FO7dnpBo8PI
 */
import Image from "next/image";
import Link from "next/link";

export function NotFound() {
  return (
    <main
      key="1"
      className="max-h-screen h-full w-full flex flex-col items-center justify-center bg-gray-100 "
    >
      <Image
        alt="404 Image"
        className="aspect-[1/1] overflow-hidden rounded-xl object-cover object-center sm:w-full"
        height={500}
        src="/images/404Image.jpg"
        width={500}
      />
      <div className="flex flex-col items-center space-y-4 absolute  ">
        <h1 className="text-4xl text-white font-bold tracking-tighter sm:text-5xl md:text-6xl/none ">
          Oops! Page not found.
        </h1>
        <p className="max-w-[600px] text-white md:text-xl text-center">
          The page you are looking for might have been removed, had its name
          changed, or is temporarily unavailable.
        </p>
        <Link
          className="inline-flex h-10 items-center justify-center rounded-md bg-cdiBlue px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-cdiLightBlue hover:text-black focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 "
          href="/"
        >
          Back to Home
        </Link>
      </div>
    </main>
  );
}
