/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SWdW42OHbHL
 */
import { Button } from "@/components/ui/button";
import {
  PopoverTrigger,
  PopoverContent,
  Popover,
} from "@/components/ui/popover";
import { Input } from "@/components/ui/input";
import { SearchButtonIcon } from "../icons/searchButtonIcon";
import { PanelTopCloseIcon } from "../icons/panelTopCloseIcon";

export function SearchIcon() {
  return (
    <Popover>
      <PopoverTrigger asChild>
        <Button size="icon" variant="outline">
          <SearchButtonIcon className="h-4 w-4" />
          <span className="sr-only">Toggle search bar</span>
        </Button>
      </PopoverTrigger>
      <PopoverContent align="start" className="w-full max-w-sm" side="left">
        <div className="flex w-full max-w-sm items-center space-x-2">
          <Input placeholder="Search" type="search" />
          <div>
            <Button size="icon" variant="outline">
              <PanelTopCloseIcon className="h-4 w-4" />
              <span className="sr-only">Close search bar</span>
            </Button>
          </div>
        </div>
      </PopoverContent>
    </Popover>
  );
}
