/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jkLGVrtCVw4
 */
import { Skeleton } from "@/components/ui/skeleton";

export function SkeletonProductLayout() {
  return (
    <div key="1" className="flex flex-col md:flex-row max-w-7xl mx-auto">
      <div className="w-full md:w-1/4">
        <div className="space-y-4 p-4">
          <Skeleton className="h-8 w-3/4" />
          <Skeleton className="h-8 w-3/4" />
          <Skeleton className="h-8 w-3/4" />
          <Skeleton className="h-8 w-3/4" />
          <Skeleton className="h-12 w-1/2" />
          <Skeleton className="h-8 w-3/4" />
          <Skeleton className="h-8 w-3/4" />
          <Skeleton className="h-8 w-3/4" />
          <Skeleton className="h-8 w-3/4" />
        </div>
      </div>
      <div className="w-full md:w-3/4 ">
        <div className="grid sm:grid-cols-2 md:grid-cols-4 gap-8">
          <div className="flex flex-col items-center">
            <Skeleton className="h-52 w-full" />
            <Skeleton className="h-6 w-3/5 mt-2" />
            <Skeleton className="h-6 w-1/2 mt-2" />
            <Skeleton className="h-10 w-3/4 mt-2" />
          </div>
          <div className="flex flex-col items-center">
            <Skeleton className="h-52 w-full" />
            <Skeleton className="h-6 w-3/5 mt-2" />
            <Skeleton className="h-6 w-1/2 mt-2" />
            <Skeleton className="h-10 w-3/4 mt-2" />
          </div>
          <div className="flex flex-col items-center">
            <Skeleton className="h-52 w-full" />
            <Skeleton className="h-6 w-3/5 mt-2" />
            <Skeleton className="h-6 w-1/2 mt-2" />
            <Skeleton className="h-10 w-3/4 mt-2" />
          </div>
          <div className="flex flex-col items-center">
            <Skeleton className="h-52 w-full" />
            <Skeleton className="h-6 w-3/5 mt-2" />
            <Skeleton className="h-6 w-1/2 mt-2" />
            <Skeleton className="h-10 w-3/4 mt-2" />
          </div>
          <div className="flex flex-col items-center">
            <Skeleton className="h-52 w-full" />
            <Skeleton className="h-6 w-3/5 mt-2" />
            <Skeleton className="h-6 w-1/2 mt-2" />
            <Skeleton className="h-10 w-3/4 mt-2" />
          </div>
          <div className="flex flex-col items-center">
            <Skeleton className="h-52 w-full" />
            <Skeleton className="h-6 w-3/5 mt-2" />
            <Skeleton className="h-6 w-1/2 mt-2" />
            <Skeleton className="h-10 w-3/4 mt-2" />
          </div>
          <div className="flex flex-col items-center">
            <Skeleton className="h-52 w-full" />
            <Skeleton className="h-6 w-3/5 mt-2" />
            <Skeleton className="h-6 w-1/2 mt-2" />
            <Skeleton className="h-10 w-3/4 mt-2" />
          </div>
          <div className="flex flex-col items-center">
            <Skeleton className="h-52 w-full" />
            <Skeleton className="h-6 w-3/5 mt-2" />
            <Skeleton className="h-6 w-1/2 mt-2" />
            <Skeleton className="h-10 w-3/4 mt-2" />
          </div>
        </div>
      </div>
    </div>
  );
}
