/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uousp2Cdvwq
 */
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { CurrencyContext } from "@/lib/context/currencyContext";
import { useContext, useEffect } from "react";
import { Label } from "../ui/label";

export function Currency() {
  const { setCurrentRate, rates, currentRate } = useContext(CurrencyContext);

  const handleCurrencyChange = (value) => {
    if (rates) {
      setCurrentRate({ code: value, rate: rates[value] });
    }
  };

  return (
    <div className="flex  items-center space-x-2">
      <Label className="text-base" htmlFor="currency">
        Currency
      </Label>
      <Select
        className="bg-white rounded-md shadow-md"
        onValueChange={handleCurrencyChange}
        defaultValue={currentRate.code}
      >
        <SelectTrigger className="w-full text-black bg-white">
          <SelectValue placeholder="Select a Currency" />
        </SelectTrigger>
        <SelectContent className="bg-white rounded-md shadow-md z-">
          <SelectItem value="USD">USD</SelectItem>
          <SelectItem value="CAD">CAD</SelectItem>
          {/* <SelectItem value="EUR">EUR</SelectItem> */}
          {/* <SelectItem value="GBP">GBP</SelectItem> */}
        </SelectContent>
      </Select>
    </div>
  );
}
