/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cpjqCKPQtSd
 */
import { Button } from "@/components/ui/button";
import Image from "next/image";
import Link from "next/link";

export function MeetTheTeam() {
  return (
    <div key="1" className="flex flex-col items-center justify-center p-6">
      <section className="w-full bg-white py-12 px-6 mb-12 rounded-lg shadow-md max-w-7xl mx-auto">
        <div className="flex flex-col md:flex-col items-center justify-between max-w-5xl w-full mx-auto">
          <div className="md:w-full text-center">
            <h1 className="text-4xl font-bold mb-4">
              Welcome to CDIfurlers.com
            </h1>
            <p className="text-lg text-gray-600 mb-6">
              where our mission is to provide reliable and innovative sailing
              solutions to our customers. We are proud to introduce you to our
              dedicated team of experts who are passionate about sailing and
              committed to delivering high-quality products and exceptional
              service.
            </p>
            <Link
              className="mb-4 md:mb-0 bg-cdiBlue text-white px-4 py-2 rounded-md hover:bg-cdiLightBlue hover:text-black transition-colors duration-200 ease-in-out"
              href={"mailto:info@cdifurlers.com"}
            >
              Join Our Team
            </Link>
          </div>
          <div className="flex md:w-full justify-center mt-6 md:mt-0">
            <Image
              alt="Hero image 1"
              className="h-48 w-48 rounded-lg"
              height="200"
              src="/images/team/cdi_square.png"
              style={{
                aspectRatio: "200/200",
                objectFit: "contain",
              }}
              width="200"
            />
            <Image
              alt="Hero image 2"
              className="h-48 w-48 rounded-lg"
              height="200"
              src="/images/team/cdi_powered_by.png"
              style={{
                aspectRatio: "200/200",
                objectFit: "contain",
              }}
              width="200"
            />
          </div>
        </div>
      </section>
      <h1 className="text-3xl font-bold mb-6">Meet the Team</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 w-fill mx-auto max-w-7xl">
        <div className="bg-gray-100 rounded-lg shadow-md p-6 flex flex-col items-center justify-center space-y-4">
          <Image
            alt="Team member 1"
            className="h-48 w-48 rounded-full mx-auto"
            height="192"
            src="/images/team/darryl.jpg"
            style={{
              aspectRatio: "192/192",
              objectFit: "cover",
            }}
            width="192"
          />
          <h2 className="text-xl font-bold text-center mt-4">Darryl Hodgson</h2>
          {/* <p className="text-center text-gray-500">Software Engineer</p> */}
          <p className="text-center text-gray-600 mt-2 ">
            Darryl has spent more time than he can remember on the water; from
            early years sailing with his family, to an exciting career helping
            boaters of all kinds in the Canadian Coast Guard. He has spent over
            a decade as the owner and operator of a well known company in the
            marine industry, building on his passion for helping everyone that
            he can to share in his enthusiasm for being on the water.
          </p>
          <Link
            className="mb-4 md:mb-0 bg-cdiBlue text-white px-4 py-2 rounded-md hover:bg-cdiLightBlue hover:text-black transition-colors duration-200 ease-in-out"
            href={"mailto:darrylhodgson@precisionsailloft.com"}
          >
            Contact Darryl
          </Link>
        </div>
        <div className="bg-gray-100 rounded-lg shadow-md p-6 flex flex-col items-center justify-center space-y-4">
          <Image
            alt="Team member 1"
            className="h-48 w-48 rounded-full mx-auto"
            height="192"
            src="/images/team/ron.jpg"
            style={{
              aspectRatio: "192/192",
              objectFit: "cover",
            }}
            width="192"
          />
          <h2 className="text-xl font-bold text-center mt-4">Ron McInnis</h2>
          {/* <p className="text-center text-gray-500">Software Engineer</p> */}
          <p className="text-center text-gray-600 mt-2 ">
            Ron grew up in Ontario, Canada where he spent summers on Lake Erie,
            Lake Huron and Lake Ontario windsurfing, sailing on Hobie Cats and
            getting addicted to all things wind powered. Ron has spent most of
            his career in sales and is always thinking of creative ways to help
            out his customers. Currently the director of sales for a large
            sailmaker, he is excited to be working with us here at
            CDIFurlers.com to bring you exceptional, informative, customer
            focused services.
          </p>
          <Link
            className="mb-4 md:mb-0 bg-cdiBlue text-white px-4 py-2 rounded-md hover:bg-cdiLightBlue hover:text-black transition-colors duration-200 ease-in-out"
            href={"mailto:info@cdifurlers.com"}
          >
            Contact Ron
          </Link>
        </div>
        <div className="bg-gray-100 rounded-lg shadow-md p-6 flex flex-col items-center justify-center space-y-4">
          <Image
            alt="Team member 1"
            className="h-48 w-48 rounded-full mx-auto"
            height="192"
            src="/images/team/dre.jpg"
            style={{
              aspectRatio: "192/192",
              objectFit: "cover",
            }}
            width="192"
          />
          <h2 className="text-xl font-bold text-center mt-4">
            Andreas Zobolas
          </h2>
          {/* <p className="text-center text-gray-500">Software Engineer</p> */}
          <p className="text-center text-gray-600 mt-2 ">
            Andreas is the Design Director for a large sail loft. He has nearly
            a decade of sail design experience and is our in house expert for
            all our questions about sails. Originally from Greece, Andreas&apos;
            family moved to Sidney, British Columbia when he was young. After
            graduating from culinary school and studying graphic design, he took
            over his family business. When presented with the opportunity for a
            change he began designing sails and has not looked back.
          </p>
          <Link
            className="mb-4 md:mb-0 bg-cdiBlue text-white px-4 py-2 rounded-md hover:bg-cdiLightBlue hover:text-black transition-colors duration-200 ease-in-out"
            href={"mailto:info@cdiFurlers.com"}
          >
            Contact Dre
          </Link>
        </div>
        <div className="bg-gray-100 rounded-lg shadow-md p-6 flex flex-col items-center justify-center space-y-4">
          <Image
            alt="Team member 1"
            className="h-48 w-48 rounded-full mx-auto"
            height="192"
            src="/images/team/laura.jpg"
            style={{
              aspectRatio: "192/192",
              objectFit: "cover",
            }}
            width="192"
          />
          <h2 className="text-xl font-bold text-center mt-4">
            Laura Pettinger
          </h2>
          {/* <p className="text-center text-gray-500">Software Engineer</p> */}
          <p className="text-center text-gray-600 mt-2 ">
            Born and raised on Vancouver Island, Laura grew up right next to the
            Pacific ocean and hasn&apos;t left. Laura has been working in
            customer service for 4 years and is just as excited to help out
            customers as she is to be a part of the CDI Furler team. Laura will
            be supporting customers with their shipping and logistic needs.
          </p>
          <Link
            className="mb-4 md:mb-0 bg-cdiBlue text-white px-4 py-2 rounded-md hover:bg-cdiLightBlue hover:text-black transition-colors duration-200 ease-in-out"
            href={"mailto:info@cdifurlers.com"}
          >
            Contact Laura
          </Link>
        </div>
        <div className="bg-gray-100 rounded-lg shadow-md p-6 flex flex-col items-center justify-center space-y-4">
          <Image
            alt="Team member 1"
            className="h-48 w-48 rounded-full mx-auto"
            height="192"
            src="/images/team/trevor.jpg"
            style={{
              aspectRatio: "192/192",
              objectFit: "cover",
            }}
            width="192"
          />
          <h2 className="text-xl font-bold text-center mt-4">Trevor Parks</h2>
          {/* <p className="text-center text-gray-500">Software Engineer</p> */}
          <p className="text-center text-gray-600 mt-2 ">
            Trevor grew up on Vancouver Island, British Columbia. He started his
            career in a big box retail environment, eventually becoming the
            customer service manager for a large store. After spending some time
            in the automotive industry he transitioned into the marine industry,
            with the same focus, providing outstanding customer service to his
            clients. Here at CDIFurlers.com Trevor is available to help you with
            any questions so you can feel confident in your decision to purchase
            with us.
          </p>
          <Link
            className="mb-4 md:mb-0 bg-cdiBlue text-white px-4 py-2 rounded-md hover:bg-cdiLightBlue hover:text-black transition-colors duration-200 ease-in-out"
            href={"mailto:trevorparks@precisionsailloft.com"}
          >
            Contact Trevor
          </Link>
        </div>
      </div>
    </div>
  );
}
