/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CyXsPgFQasv
 */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import LoadingSpinner from "../ui/loadingSpinner";

export function Quantity({
  setQuantity,
  quantity,
  min,
  loading,
  handleRemove,
}) {
  const handleQuantity = (e) => {
    const val = Number(e.target.value);

    if (Number.isInteger(val) && val >= min) {
      setQuantity(val);
      if (handleRemove && val === 0) {
        handleRemove();
      }
    }
  };

  const increaseQuantity = async (n = 1) => {
    const val = Number(quantity) + n;
    if (Number.isInteger(val) && val >= min) {
      setQuantity(val);
      if (handleRemove && val === 0) {
        await handleRemove();
      }
    }
  };

  return (
    <div key="1" className="flex items-center gap-2 justify-start">
      <Button
        className="border-none flex justify-center align-center"
        size="icon"
        variant="outline"
        onClick={(e) => {
          e.preventDefault();
          increaseQuantity(-1);
        }}
      >
        <MinusIcon className="h-4 w-4" />
        <span className="sr-only">Decrease quantity</span>
      </Button>
      {loading ? (
        <span className="w-12 h-10 text-center border border-gray-200 flex justify-center item-center rounded-md border border-gray-200 bg-white ">
          <LoadingSpinner />
        </span>
      ) : (
        <Input
          className="w-12 text-center border border-gray-200  [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
          // max="10"
          min="1"
          type="number"
          value={quantity}
          onChange={handleQuantity}
        />
      )}
      <Button
        className="border-none flex justify-center align-center"
        size="icon"
        variant="outline"
        onClick={(e) => {
          e.preventDefault();
          increaseQuantity(1);
        }}
      >
        <PlusIcon className="h-6 w-6" />
        <span className="sr-only">Increase quantity</span>
      </Button>
    </div>
  );
}

function MinusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
    </svg>
  );
}

function PlusIcon(props) {
  return (
    <svg
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path
        d="M12 5V19"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M5 12H19"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}
