/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gGGBFYpGNpj
 */
import { Badge } from "@/components/ui/badge"

export function quantityIndicator() {
  return (
    (<div className="relative inline-block">
      <ShoppingCartIcon className="h-6 w-6" />
      <Badge
        className="absolute top-0 right-0 transform translate-x-1/2 -translate-y-1/2 h-5 w-5 text-xs flex items-center justify-center rounded-full bg-red-500 text-white">
        3
      </Badge>
    </div>)
  );
}


function ShoppingCartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 1.58h9.78a2 1.95-1.57l1.65-7.43H5.12" />
    </svg>)
  );
}
