/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/X1rr5OVS6SS
 */
import {
  AccordionTrigger,
  AccordionContent,
  AccordionItem,
  Accordion,
} from "@/components/ui/accordion";
import { RadioGroupItem, RadioGroup } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";

export function radio() {
  return (
    <div
      key="1"
      className="grid md:grid-cols-[240px_1fr] gap-10 items-start max-w-6xl px-4 mx-auto py-6"
    >
      <div className="flex flex-col gap-4 items-start">
        <h2 className="text-2xl font-bold tracking-tight">Filters</h2>
        <Accordion className="w-full" collapsible type="single">
          <AccordionItem value="price">
            <AccordionTrigger className="text-base">Price</AccordionTrigger>
            <AccordionContent>
              <div className="grid gap-2">
                <RadioGroup defaultValue="price-under-25">
                  <Label className="flex items-center gap-2 font-normal">
                    <RadioGroupItem
                      id="price-under-25"
                      value="price-under-25"
                    />
                    Under $25
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <RadioGroupItem id="price-25-50" value="price-25-50" />
                    $25 to $50
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <RadioGroupItem id="price-50-100" value="price-50-100" />
                    $50 to $100
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <RadioGroupItem id="price-100-200" value="price-100-200" />
                    $100 to $200
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <RadioGroupItem
                      id="price-200-above"
                      value="price-200-above"
                    />
                    $200 & Above
                  </Label>
                </RadioGroup>
              </div>
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="brand">
            <AccordionTrigger className="text-base">Brand</AccordionTrigger>
            <AccordionContent>
              <div className="grid gap-2">
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="brand-apple" />
                  Apple
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="brand-samsung" />
                  Samsung
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="brand-sony" />
                  Sony
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="brand-microsoft" />
                  Microsoft
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="brand-adidas" />
                  Adidas
                </Label>
              </div>
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  );
}
