/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SWdW42OHbHL
 */
import { Button } from "@/components/ui/button";
import {
  PopoverTrigger,
  PopoverContent,
  Popover,
} from "@/components/ui/popover";
import { Input } from "@/components/ui/input";
import { SearchButtonIcon } from "../icons/searchButtonIcon";
import { PanelTopCloseIcon } from "../icons/panelTopCloseIcon";
import { useRouter } from "next/router";

export function SearchIcon() {
  const router = useRouter();

  const handleSearch = (e) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const data = Array.from(formData.keys()).reduce((acc, key) => {
      acc[key] = formData.get(key);
      return acc;
    }, {});
    if (data.search !== "") {
      router.push({
        pathname: "/products",
        query: {
          search: data.search,
        },
      });
    }
  };

  return (
    <Popover>
      <PopoverTrigger asChild>
        <Button size="icon" variant="outline">
          <SearchButtonIcon className="h-4 w-4" />
          <span className="sr-only">Toggle search bar</span>
        </Button>
      </PopoverTrigger>
      <PopoverContent align="start" className="w-full max-w-sm" side="bottom">
        <form
          className="flex w-full max-w-sm items-center space-x-2"
          onSubmit={handleSearch}
        >
          <Input
            placeholder="Search"
            name="search"
            type="search"
            onKeyDown={(e) => (e.key === "Enter" ? handleSearch : "")}
          />
          <div>
            <Button size="icon" variant="outline">
              <PanelTopCloseIcon className="h-4 w-4" />
              <span className="sr-only">Close search bar</span>
            </Button>
          </div>
        </form>
      </PopoverContent>
    </Popover>
  );
}
