/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/f9AKLbBWz50
 */
import { Button } from "@/components/ui/button";
import {
  DropdownMenuTrigger,
  DropdownMenuRadioItem,
  DropdownMenuRadioGroup,
  DropdownMenuContent,
  DropdownMenu,
} from "@/components/ui/dropdown-menu";

export function SortBy() {
  return (
    <div
      key="1"
      className="grid md:grid-cols-[240px_1fr] items-start max-w-6xl  "
    >
      <div className="grid gap-6 md:gap-8">
        <div className="flex flex-col md:flex-row items-start md:items-center gap-4 md:gap-8">
          <div className="flex items-center gap-4">
            <span className="text-base font-medium">Sort by:</span>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button className="shrink-0" variant="outline">
                  <ArrowUpDownIcon className="w-4 h-4 mr-2" />
                  Select
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-[200px]">
                <DropdownMenuRadioGroup value="price-asc">
                  <DropdownMenuRadioItem value="price-asc">
                    Price: Low to High
                  </DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="price-desc">
                    Price: High to Low
                  </DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="date-asc">
                    Date Added: Recent First
                  </DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="date-asc">
                    Date Added: Oldest First
                  </DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="title-asc">
                    Name: A to Z
                  </DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="title-desc">
                    Name: Z to A
                  </DropdownMenuRadioItem>
                </DropdownMenuRadioGroup>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
        <div className="grid sm:grid-cols-2 md:grid-cols-4 gap-8" />
      </div>
    </div>
  );
}

function ArrowUpDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21 16-4 4-4-4" />
      <path d="M17 20V4" />
      <path d="m3 8 4-4 4" />
      <path d="M7 4v16" />
    </svg>
  );
}
