/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/B7g0kG2pufH
 */
import Link from "next/link";
import { useRouter } from "next/router";

export function ThankYouPage() {
  const router = useRouter();
  return (
    <section
      key="1"
      className="w-full flex justify-center py-12 md:py-24 lg:py-32"
    >
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
              Thanks for Ordering from CDI Furlers!
            </h2>
            <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed  mx-auto">
              Your order has been received and is being processed. We appreciate
              you choosing to purchase from us and we are excited to help you to
              continue sailing.
            </p>
          </div>
          <div className="bg-white shadow-lg rounded-lg p-6 md:p-8 lg:p-10 w-full md:w-3/4 lg:w-1/2">
            <div className="grid gap-4 md:gap-6">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Order Number</h3>
                <p className="text-sm text-gray-500 ">
                  #{!router.query.order_id ? "" : router.query.order_id}
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Delivery Timeline</h3>
                <p className="text-sm text-gray-500 ">
                  Please note that delivery typically takes place 5-7 weeks
                  after order confirmation.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Customer Support</h3>
                <p className="text-sm text-gray-500 ">
                  If you have any questions or need assistance with your order,
                  please contact our customer support team at
                  info@cdifurlers.com or call 1-(888)-880-6813. We’re here to
                  help!
                </p>
              </div>
            </div>
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-cdiBlue px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-cdiLightBlue hover:text-black focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50  mt-6"
              href="#"
            >
              Continue Shopping
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}
